repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args:
          - --line-length=80

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=80
          - --ignore=E203,E501,F401,W503
